[DEFAULT]
update_interval_seconds = 0.2
use_live_data = false
wav_file_dir = wav_files/
wav_file = Ammani.wav
play_sounds = false

[NSP]
com_port = /dev/tty.usbserial-DM89ON8K
baud_rate = 230400
sample_rate = 10000

[UI]
; how many data points per second are plotted. Decrease for better front end performance.
plot_samples_per_second = 50
; plot will scroll right when new data is added. Display last N seconds of data.
plot_last_n_seconds = 10
; Number of frequency bins in the frequency-magnitude plot. Decrease for better front end performance.
frequency_plot_bins = 50

[FILTERS]
grid_frequency = 60