[DEFAULT]
update_interval_seconds = 0.2
use_live_data = false
wav_file_dir = demo_wav_files/
wav_file = Elis 2.wav
play_sounds = true
; initial range (lower->upper) of RMS values, between which notes will be played
init_lower_rms_audio_val = 5
init_upper_rms_audio_val = 1000

[NSP]
com_port = /dev/tty.usbserial-DM89ON8K
baud_rate = 230400
sample_rate = 10000

[UI]
; how many data points per second are plotted. Decrease for better front end performance.
plot_samples_per_second = 20
; plot will scroll right when new data is added. Display last N seconds of data.
plot_last_n_seconds = 10
; Number of frequency bins in the frequency-magnitude plot. Decrease for better front end performance.
frequency_plot_bins = 50

[FILTERS]
grid_frequency = 60
bandpass_min = 20
bandpass_max = 450

[SAVE]
save_recording = true
; max recording time in seconds (recording data will be overwritten beyond this)
max_recording_time = 20
